### ISSUE TITLE
PPA from the installation guide doesn't work

### ISSUE THREAD

**Issue by in-in** [usebruno/bruno#1427]
I get "404 page not found"
![24021201750](https://github.com/usebruno/bruno/assets/8797432/30d75777-50f9-4372-bce9-d4c76508d72a)

https://www.usebruno.com/downloads
![24021201815](https://github.com/usebruno/bruno/assets/8797432/f4a3c3ed-28c9-408c-8798-daa0cdc791d4)

```sh
➜  sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266 
[sudo] password for mint:     
gpg: keybox '/etc/apt/keyrings/bruno.gpg' created
gpg: failed to create temporary file '/root/.gnupg/.#lk0x000055cb2ad809e0.VirtualBox.2928': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
~ as 🧙 
✗  echo "deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable" | sudo tee /etc/apt/sources.list.d/bruno.list 
deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable
~ as 🧙 
➜  sudo apt update 
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                                    
Hit:3 https://ppa.launchpadcontent.net/hluk/copyq/ubuntu jammy InRelease                                                                                                                                          
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                                                                                            
Hit:5 https://ppa.launchpadcontent.net/kelleyk/emacs/ubuntu jammy InRelease                                                                                                                                       
Hit:6 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease                                                                                                                                        
Hit:7 https://deb.librewolf.net jammy InRelease                                                                                                                                                                   
Hit:8 https://apt.syncthing.net syncthing InRelease                                                                                                                                         
Hit:9 https://packages.microsoft.com/repos/code stable InRelease                                                                      
Get:10 https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04  InRelease [1,557 B]      
Ign:11 http://packages.linuxmint.com virginia InRelease                                                 
Hit:12 https://ppa.launchpadcontent.net/inkscape.dev/stable/ubuntu jammy InRelease
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:14 https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu jammy InRelease
Hit:15 https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu jammy InRelease
Hit:16 http://packages.linuxmint.com virginia Release                           
Hit:17 https://ppa.launchpadcontent.net/unit193/encryption/ubuntu jammy InRelease
Hit:18 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:20 http://debian.usebruno.com bruno InRelease
Err:21 http://debian.usebruno.com bruno Release
  404  Not Found [IP: 137.184.34.252 80]
Reading package lists... Done
E: The repository 'http://debian.usebruno.com bruno Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
~ as 🧙 
✗  

```

**Comment by helloanoop** [comment]
@in-in @vmarinescu 

I have fixed this issue. Can you try again?

**Comment by in-in** [comment]
There was another error related to the public key
```sh
➜  sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266 
[sudo] password for mint:     
gpg: keybox '/etc/apt/keyrings/bruno.gpg' created
gpg: failed to create temporary file '/root/.gnupg/.#lk0x000055ef118099e0.VirtualBox.2615': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
~ as 🧙 
✗  
~ as 🧙 
➜  echo "deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable" | sudo tee /etc/apt/sources.list.d/bruno.list 
deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable
~ as 🧙 
➜  sudo apt update 
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                                    
Hit:3 https://ppa.launchpadcontent.net/hluk/copyq/ubuntu jammy InRelease                                                                                                                                          
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                                                                                            
Ign:5 http://packages.linuxmint.com virginia InRelease                                                                                                                                                            
Hit:6 https://ppa.launchpadcontent.net/kelleyk/emacs/ubuntu jammy InRelease                                                                                                                            
Hit:7 https://deb.librewolf.net jammy InRelease                                                                                                                        
Get:8 https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04  InRelease [1,557 B]                                                              
Hit:9 https://packages.microsoft.com/repos/code stable InRelease                                                                                                                    
Get:10 http://debian.usebruno.com bruno InRelease [1,812 B]                                                                                      
Hit:11 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease               
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:13 https://ppa.launchpadcontent.net/inkscape.dev/stable/ubuntu jammy InRelease
Hit:14 http://packages.linuxmint.com virginia Release                           
Hit:15 https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu jammy InRelease
Hit:16 https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu jammy InRelease
Hit:17 https://ppa.launchpadcontent.net/unit193/encryption/ubuntu jammy InRelease
Hit:18 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Err:10 http://debian.usebruno.com bruno InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC
Hit:20 https://apt.syncthing.net syncthing InRelease
Reading package lists... Done
W: GPG error: http://debian.usebruno.com bruno InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC
E: The repository 'http://debian.usebruno.com bruno InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by helloanoop** [comment]
`gpg: keyserver receive failed: No dirmngr`

@in-in  I think its failing due to because `dirmngr` is missing.

`apt install dirmngr`

Here is what I have on my system
```bash    
root@dev-ubuntu:~# dpkg -l | grep dirmngr
ii  dirmngr                         2.2.40-1.1ubuntu1                       amd64        GNU privacy guard - network certificate management service
```

If everything goes well, then you should be able to successfully add the GPG key
Here is a log of a successful GPG key import
```bash
root@dev-ubuntu:~# sudo mkdir -p /etc/apt/keyrings 
root@dev-ubuntu:~# sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266
gpg: keybox '/etc/apt/keyrings/bruno.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 9FA6017ECABE0266: public key "Anoop M D <anoop.md1421@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

PS: If things are still failing, a temporary workaround would be to install bruno from [snap](https://snapcraft.io/install/bruno/ubuntu) or [flatpak](https://flathub.org/apps/com.usebruno.Bruno)

**Comment by in-in** [comment]
`dirmngr` is already installed on the system

```sh
➜  dpkg -l | grep dirmngr
ii  dirmngr                                        2.2.27-3ubuntu2.1                                    amd64        GNU privacy guard - network certificate management service
```

**Comment by vmarinescu** [comment]
> @in-in @vmarinescu
> 
> I have fixed this issue. Can you try again?

for me it is working now, thanks

**Comment by in-in** [comment]
This works in my case:
```sh
sudo gpg \
--homedir /tmp \
--no-default-keyring \
--keyring /etc/apt/keyrings/bruno.gpg \
--keyserver keyserver.ubuntu.com \
--recv-keys 9FA6017ECABE0266
```

```sh
mint@VirtualBox:~$ sudo gpg \
--homedir /tmp \
--no-default-keyring \
--keyring /etc/apt/keyrings/bruno.gpg \
--keyserver keyserver.ubuntu.com \
--recv-keys 9FA6017ECABE0266
[sudo] password for mint:     
gpg: keybox '/etc/apt/keyrings/bruno.gpg' created
gpg: /tmp/trustdb.gpg: trustdb created
gpg: key 9FA6017ECABE0266: public key "Anoop M D <anoop.md1421@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
mint@VirtualBox:~$ echo "deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable" | sudo tee /etc/apt/sources.list.d/bruno.list
deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable
mint@VirtualBox:~$ sudo apt update
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:3 http://packages.linuxmint.com virginia InRelease
Get:4 http://debian.usebruno.com bruno InRelease [1,812 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:6 http://packages.linuxmint.com virginia Release
Get:7 http://debian.usebruno.com bruno/stable amd64 Packages [478 B]
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease 
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,282 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages [552 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe i386 Packages [681 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,031 kB]
Fetched 3,778 kB in 2s (1,800 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'http://debian.usebruno.com bruno InRelease' doesn't support architecture 'i386'
mint@VirtualBox:~$ sudo apt install bruno
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  bruno
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 70.4 MB of archives.
After this operation, 283 MB of additional disk space will be used.
Get:1 http://debian.usebruno.com bruno/stable amd64 bruno amd64 1.6.1 [70.4 MB]
Fetched 70.4 MB in 8s (8,338 kB/s)
Selecting previously unselected package bruno.
(Reading database ... 528554 files and directories currently installed.)
Preparing to unpack .../archives/bruno_1.6.1_amd64.deb ...
Unpacking bruno (1.6.1) ...
Setting up bruno (1.6.1) ...
Processing triggers for desktop-file-utils (0.26+mint3+victoria) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
mint@VirtualBox:~$ 

```

**Comment by qupada** [comment]
@helloanoop I'm not sure this issue is entirely resolved, I'm still getting a public key error.

Using KDE Neon (effectively Ubuntu 22.04) here.

Seeing repository signed by `56333D3B745C1FEC` and not `9FA6017ECABE0266`, but the key is already installed.

```
Err:15 http://debian.usebruno.com bruno InRelease                                                                             
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC
```
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://debian.usebruno.com bruno InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC
```
```
# gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266
gpg: key 9FA6017ECABE0266: "Anoop M D <anoop.md1421@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Using `56333D3B745C1FEC` with the `--recv-keys` command downloads that same `9FA6017ECABE0266` key though:
```
# gpg --no-default-keyring --keyring /tmp/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 56333D3B745C1FEC
gpg: keybox '/tmp/bruno.gpg' created
gpg: key 9FA6017ECABE0266: public key "Anoop M D <anoop.md1421@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

```
/tmp/bruno.gpg
--------------
pub   rsa4096 2023-10-12 [SC] [expires: 2025-10-11]
      E598552E09C999055FEFA7159FA6017ECABE0266
uid           [ unknown] Anoop M D <anoop.md1421@gmail.com>
sub   rsa4096 2023-10-12 [S] [expires: 2025-10-11]
sub   rsa4096 2023-10-12 [E] [expires: 2025-10-11]

/etc/apt/keyrings/bruno.gpg
---------------------------
pub   rsa4096 2023-10-12 [SC] [expires: 2025-10-11]
      E598552E09C999055FEFA7159FA6017ECABE0266
uid           [ unknown] Anoop M D <anoop.md1421@gmail.com>
sub   rsa4096 2023-10-12 [S] [expires: 2025-10-11]
sub   rsa4096 2023-10-12 [E] [expires: 2025-10-11]
```

Downloading the repository metadata and attempting to verify it does complain about use of the sub-key:

```
# curl -o /tmp/InRelease http://debian.usebruno.com/dists/bruno/InRelease
# gpg --verbose --verify --keyring /etc/apt/keyrings/bruno.gpg /tmp/InRelease 
gpg: armor header: Hash: SHA512
gpg: original file name=''
gpg: Signature made Mon 22 Jan 2024 12:32:47 NZDT
gpg:                using RSA key B5686F65CAA08C49040D6E3F56333D3B745C1FEC
gpg: using subkey 56333D3B745C1FEC instead of primary key 9FA6017ECABE0266
gpg: using subkey 56333D3B745C1FEC instead of primary key 9FA6017ECABE0266
gpg: using pgp trust model
gpg: Good signature from "Anoop M D <anoop.md1421@gmail.com>" [unknown]
gpg: using subkey 56333D3B745C1FEC instead of primary key 9FA6017ECABE0266
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: E598 552E 09C9 9905 5FEF  A715 9FA6 017E CABE 0266
     Subkey fingerprint: B568 6F65 CAA0 8C49 040D  6E3F 5633 3D3B 745C 1FEC
gpg: textmode signature, digest algorithm SHA512, key algorithm rsa4096
```

As an aside, I've also had to amend the `sources.list.d` file to clear the "no i386 architecture" warning:
```
deb [signed-by=/etc/apt/keyrings/bruno.gpg][arch=amd64] http://debian.usebruno.com/ bruno stable
```
```
N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'http://debian.usebruno.com bruno InRelease' doesn't support architecture 'i386'
```

**Comment by helloanoop** [comment]
@qupada I have fixed the signing issue. Can you please try again ?

**Comment by qupada** [comment]
Still the same subkey error I'm afraid:

```
# curl -o /tmp/InRelease http://debian.usebruno.com/dists/bruno/InRelease
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1812  100  1812    0     0   3104      0 --:--:-- --:--:-- --:--:--  3108
```

(File shows timestamp of around 4 minutes before your comment, so definitely a fresh copy)

```
# gpg --verbose --verify --keyring /etc/apt/keyrings/bruno.gpg /tmp/InRelease
gpg: armor header: Hash: SHA512
gpg: original file name=''
gpg: Signature made Wed 24 Jan 2024 21:39:06 NZDT
gpg:                using RSA key B5686F65CAA08C49040D6E3F56333D3B745C1FEC
gpg: using subkey 56333D3B745C1FEC instead of primary key 9FA6017ECABE0266
gpg: using subkey 56333D3B745C1FEC instead of primary key 9FA6017ECABE0266
gpg: using pgp trust model
gpg: Good signature from "Anoop M D <anoop.md1421@gmail.com>" [unknown]
gpg: using subkey 56333D3B745C1FEC instead of primary key 9FA6017ECABE0266
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: E598 552E 09C9 9905 5FEF  A715 9FA6 017E CABE 0266
     Subkey fingerprint: B568 6F65 CAA0 8C49 040D  6E3F 5633 3D3B 745C 1FEC
gpg: textmode signature, digest algorithm SHA512, key algorithm rsa4096
```
```
# gpg --verbose --search-keys --keyserver hkp://keyserver.ubuntu.com:80 56333D3B745C1FEC
gpg: data source: http://185.125.188.26:80
(1)     Anoop M D <anoop.md1421@gmail.com>
          4096 bit RSA key 9FA6017ECABE0266, created: 2023-10-12
Keys 1-1 of 1 for "56333D3B745C1FEC".  Enter number(s), N)ext, or Q)uit > 1
gpg: data source: http://185.125.188.26:80
gpg: armor header: Comment: Hostname:
gpg: armor header: Version: Hockeypuck 2.1.1-10-gec3b0e7
gpg: pub  rsa4096/9FA6017ECABE0266 2023-10-12  Anoop M D <anoop.md1421@gmail.com>
gpg: key 9FA6017ECABE0266: "Anoop M D <anoop.md1421@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Thanks

**Comment by RayAuxey** [comment]
I have the same issue

**Comment by crivotz** [comment]
Same problem for me on Debian 12.
For now, install the appimage via zinit
```(shell)
# BRUNO
zinit ice from="gh-r" as="program" bpick="*appimage*" mv="bruno* -> bruno" pick="bruno"
zinit light usebruno/bruno
```

**Comment by timwsuqld** [comment]
I am still having the issue in Ubuntu 22.04
```
$ curl -o /tmp/InRelease http://debian.usebruno.com/dists/bruno/InRelease
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1812  100  1812    0     0   2723      0 --:--:-- --:--:-- --:--:--  2724
# gpg --verbose --verify --keyring /etc/apt/keyrings/bruno.gpg /tmp/InRelease
gpg: armour header: Hash: SHA512
gpg: original file name=''
gpg: Signature made Wed 13 Mar 2024 04:51:32 AWST
gpg:                using RSA key B5686F65CAA08C49040D6E3F56333D3B745C1FEC
gpg: Can't check signature: No public key
```
Doesn't complain about subkey, but still has the same `56333D3B745C1FEC` ID error. Apt gives `W: GPG error: http://debian.usebruno.com bruno InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC`

**Comment by GimpMaster** [comment]
I had the same issue in Ubuntu 22.04 following the website instructions. I had to run the gpg command below which fixed it

```
sudo gpg \
--homedir /tmp \
--no-default-keyring \
--keyring /etc/apt/keyrings/bruno.gpg \
--keyserver keyserver.ubuntu.com \
--recv-keys 9FA6017ECABE0266
```

After running that it imported properly and I was about to apt update and apt install

**Comment by PicchiSeba** [comment]
Thanks @GimpMaster, that fixed it for me!

**Comment by ijash** [comment]
i got error
```
N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'http://debian.usebruno.com bruno InRelease' doesn't support architecture 'i386'

```

**Comment by paucapo** [comment]
To fix the error with i386, change the file `/etc/apt/sources.list.d/bruno.list` to:
```
deb [arch=amd64 signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable
```

It would be good to change in the website too, if in the future there is an arm64 build this should be taken into account.

**Comment by Rakasa** [comment]
I'm getting 
```
$ sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266
gpg: keyserver receive failed: End of file
```

Is this the same issue or a separate issue?

**Comment by richard-scott** [comment]
@Rakasa 

> Is this the same issue or a separate issue?

Same, use [this](https://github.com/usebruno/bruno/issues/1427#issuecomment-2032952703) fix and [this](https://github.com/usebruno/bruno/issues/1427#issuecomment-2237105533) fix.

**Comment by caerulescens** [comment]
> I had the same issue in Ubuntu 22.04 following the website instructions. I had to run the gpg command below which fixed it
> 
> ```
> sudo gpg \
> --homedir /tmp \
> --no-default-keyring \
> --keyring /etc/apt/keyrings/bruno.gpg \
> --keyserver keyserver.ubuntu.com \
> --recv-keys 9FA6017ECABE0266
> ```
> 
> After running that it imported properly and I was about to apt update and apt install

This fixed the issue for Debian 12 (Bookworm); as of writing this, the Linux installation instructions do not work on the website.

**Comment by Cruel** [comment]
The original error: `gpg: keyserver receive failed: No dirmngr`
is probably caused by initial gpg dirs not existing. This can be fixed by running `sudo gpg -k`.
However, the key still does not work. And changing the homedir to /tmp (like above comment) does not fix this either.

```bash
$ sudo gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266
gpg: keyserver receive failed: Server indicated a failure
$ sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266
gpg: keyserver receive failed: Server indicated a failure
```

The cause is discussed here:
https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure

There is a deeper DNS problem at work here with dirmngr or something, but changing to port 80 worked without any other system changes:
```
sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 9FA6017ECABE0266
```
Other tools can connect just fine to the keyserver:
```
$ nc -vz keyserver.ubuntu.com 11371
Connection to keyserver.ubuntu.com (185.125.188.26) 11371 port [tcp/hkp] succeeded!
```

I'm not sure if it's appropriate to change that command in the documentation, but there should at least be a note about this common problem.

**Comment by centic9** [comment]
For me the ` curl` command from [here](https://www.usebruno.com/downloads) work.

But the `gpg` command from [here](http://debian.usebruno.com/) does NOT work.

Using `gpg` leads to a smaller key-file where apt fails with `EOF` when reading the key.

`curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9FA6017ECABE0266" | gpg --dearmor | sudo tee /etc/apt/keyrings/bruno.gpg > /dev/null`
`gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266`
