### ISSUE TITLE
Error generating code snippet

### ISSUE THREAD

**Issue by eyayaw** [usebruno/bruno#1584]
Hi there,

Bruno's `(v 1.9.0)` code generation fails on some API entries for me. It has been working for me since the feature was introduced. The only change I made was recently using the `.env` feature for environment variables. My environment variables setup works fine.

![](https://github.com/usebruno/bruno/assets/49317723/d6328437-2f5f-49ef-aa4f-8d1f42b3544a)

**Comment by oklaiss** [comment]
I'm seeing this as well on v1.12.1. It was working on v1.10.0

**Comment by ujaehrig** [comment]
Updated to v1.13.1 
The error still occurs. Is there any way to see, what the error is?

**Comment by ponsfrilus** [comment]
Updated to v1.16.1, but still have the issue. Toggling developer tools don't help that much:
![image](https://github.com/usebruno/bruno/assets/176002/147a1517-4b37-4082-9e88-acdea1a2afde)

**Comment by ernstki** [comment]
Attempted with 1.12.3 and the latest as of this writing, 1.17.0, on Intel Mac. The earlier version reports an error similar to the one reported here. The up-to-date 1.17 version does not have the issue—for my particular use case.

Sanitized `collection.bru` and `RequestName.bru`, including the output from the dev console in 1.12.3 below.

```
# collection.bru
auth {
  mode: bearer
}

auth:bearer {
  token: SuperSecretTokenString
}
```

```
# environments/prod.bru
vars {
  api: https://the.internal.url/gitlab/api/v4
}
```

```
# Search.bru
meta {
  name: Search
  type: http
  seq: 3
}

get {
  url: {{api}}/search?scope=blobs&search="module load"
  body: none
  auth: none
}

query {
  scope: blobs
  search: "some search query"
}
```

### Screenshot of dev console in 1.12.3

![Screenshot of the backtrace in the dev console with 1.12.3](https://github.com/usebruno/bruno/assets/4009681/dc49419e-84bc-46bc-bb91-ed5363b8f899)

The current 1.17.0 build does not produce any error in the Chrome/Electron console. Hard to say if _my_ problem was the _exact same_ as that of @eyayaw's original report, though.

### See if updating to a newer build fixes it, regardless

Either way, I recommend trying the latest version if you are somewhere in between and seeing this error, regardless of what error message shows up in the Chrome/Electron dev console, I'd recommend trying the latest version and seeing this error goes away—regardless of what error message shows up in the Chrome/Electron dev console.

**Comment by blazindrop** [comment]
I had the same issue. The cause was my POST request was sending URL parameters for the payload. When I moved them to use Body multipart form or form url coded the export worked.

**Comment by merc1er** [comment]
@helloanoop This now displays "Oops! Something went wrong" when trying to generate code on version 1.19.0:
![image](https://github.com/usebruno/bruno/assets/21960643/3eb0b2d7-0e38-44d6-97d9-fc7d14d20338)

**Comment by Bonnev** [comment]
Hey guys. I guess it gives different errors in different cases. My case was the "validation failed" and it was an issue with the GET params - they had spaces (which worked fine as a request, but failed for the export). When I encoded it (e.g. via https://www.urlencoder.io/) it worked.

Note: some unencoded parts don't even work in params.

So what should be fixed for this specific case is to allow unencoded values in the params and automatically encode them when sending the request and when exporting.

**Comment by flav1972** [comment]
for me on windows (v1.18.0). error unknown keyword "afterRequest"
![image](https://github.com/usebruno/bruno/assets/3330689/70d6283c-6fdb-4388-9dc7-e9a8bd6a459d)
as @arnaduga above.

**Comment by tadams1138** [comment]
Similar problem but mentions "Cannot read properties of undefined (reading 'externalSecrets')". v1.19.0 of Bruno
![image](https://github.com/user-attachments/assets/e8fe4475-1f33-4e49-80e8-98411d661bf7)
![image](https://github.com/user-attachments/assets/b4c2fea5-187b-44cc-9aa2-428a605152f4)

**Comment by Its-treason** [comment]
> Similar problem but mentions "Cannot read properties of undefined (reading 'externalSecrets')". v1.19.0 of Bruno ![image](https://private-user-images.githubusercontent.com/8430612/351378649-e8fe4475-1f33-4e49-80e8-98411d661bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTU0MTAsIm5iZiI6MTcyMTc1NTExMCwicGF0aCI6Ii84NDMwNjEyLzM1MTM3ODY0OS1lOGZlNDQ3NS0xZjMzLTRlNDktODBlOC05ODQxMWQ2NjFiZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTcxODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU3NjkyYThkNmM2YmM3NzkxNjk5NTY3OGYxZTFhM2UxMjM5ZDM5OTE2YzQ3N2Q0NWRkNjljYjlmOWVjYTE1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a7irVe1QAQr58bQBvI7dtdJCIy1_krq0LB3lJaC7DNQ) ![image](https://private-user-images.githubusercontent.com/8430612/351379124-b4c2fea5-187b-44cc-9aa2-428a605152f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTU0MTAsIm5iZiI6MTcyMTc1NTExMCwicGF0aCI6Ii84NDMwNjEyLzM1MTM3OTEyNC1iNGMyZmVhNS0xODdiLTQ0Y2MtOWFhMi00MjhhNjA1MTUyZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTcxODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VjYTQ5YTJlZDE4Y2U3YjVmZjEzZjI4MDBjYzE5ODM2MmI4MjM5N2FjNTBlMjVmMDk0YWVjZjgwMDA5NDJlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qwYuZ2nHGXnpM4XPVkrDnQEJCUK_QZAjJTIidF8BceE)

Update your installation, this was fixed with 1.20.0

**Comment by tadams1138** [comment]
Thanks @lts-treason ! That fixed it.

**Comment by mehmoodak** [comment]
Updated to `v1.23.1` and still facing error while generating code.

```
TypeError: Cannot read properties of undefined (reading 'filter')
    at createPostData (557-d94615abd63cd33c.js:1:445738)
    at buildHarRequest (557-d94615abd63cd33c.js:1:446135)
    at GenerateCodeItem_CodeView (557-d94615abd63cd33c.js:1:447320)
    at Xh (framework-80ea8c0f440c6a32.js:9:60991)
    at dj (framework-80ea8c0f440c6a32.js:9:72858)
    at x (framework-80ea8c0f440c6a32.js:9:120345)
    at Vk (framework-80ea8c0f440c6a32.js:9:99131)
    at framework-80ea8c0f440c6a32.js:9:98998
    at Jk (framework-80ea8c0f440c6a32.js:9:99005)
    at Fk (framework-80ea8c0f440c6a32.js:9:96095)
```

**Comment by sanjai0py** [comment]
Hey @mehmoodak, will it be possible for you to share the `.bru` file?

**Comment by mehmoodak** [comment]
@sanjai0py not sure what's changed but its working fine now 🤷‍♂️

**Comment by darcien** [comment]
I'm using Bruno v1.35.0 and could repro the error using this bru file:

```bru
meta {
  name: Foo
  type: http
  seq: 3
}

post {
  url: https://example.com
  body: formUrlEncoded
  auth: none
}
```

It's a request that specify request body content type but left the body empty.


![image](https://github.com/user-attachments/assets/851483c2-6afd-4409-bf9c-3882e9b9dc99)

**Comment by anusree-bruno** [comment]
This issue has been fixed in this PR https://github.com/usebruno/bruno/pull/4752
