### ISSUE TITLE
When specifying "No Body" a Content-Type header is still sent

### ISSUE THREAD

**Issue by jsonfry** [usebruno/bruno#1693]
When doing a POST, PUT, or PATCH with the "No Body" option selected, a `Content-Type` header is sent with the value of `application/x-www-form-urlencoded`.

There should be no content type header sent

[Jira](https://usebruno.atlassian.net/browse/BRU-1929)

**Comment by sanjai0py** [comment]
Can you check if this issue is happening in the latest version of Bruno, @jsonfry?

**Comment by orgrimarr** [comment]
Got same issue using bruno `v1.13.1` running on ubuntu (using apt repository release)

**Comment by jsonfry** [comment]
Yes, still a probelm on 1.14.0. 

Here's a simple Python server that responses with the request headers as the body:

```python
from http.server import BaseHTTPRequestHandler, HTTPServer

class RequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self._print_headers()

    def do_POST(self):
        self._print_headers()

    def _print_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/plain')
        self.end_headers()
        for header, value in self.headers.items():
            self.wfile.write(f"{header}: {value}\n".encode('utf-8'))

def run(server_class=HTTPServer, handler_class=RequestHandler, port=8000):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    print(f"Server running on port {port}")
    httpd.serve_forever()

if __name__ == "__main__":
    run()
```

And here it is running, notice the returned header value for Content-Type, even though "no body" is selected:

 <img width="1456" alt="Screenshot 2024-04-26 at 12 18 01" src="https://github.com/usebruno/bruno/assets/368400/b9b41b61-97b4-43c0-acf5-fea97089e518">

**Comment by notaphplover** [comment]
Recreated with latest version so far (1.27.0)

**Comment by sanjai0py** [comment]
Hey everyone, I was able to reproduce this bug. It seems like Axios is setting a default `'Content-Type': 'application/x-www-form-urlencoded'` header, which we should override. We will get this fixed soon!

https://github.com/axios/axios/blob/9588fcdec8aca45c3ba2f7968988a5d03f23168c/lib/defaults/index.js#L12-L14

**Comment by howard-repos** [comment]
any update? still got the same problem in version 1.33.0

**Comment by devjos** [comment]
Any update? Problem still persists in v1.38.1

**Comment by betawait** [comment]
Hi I ran into this as well. I don't think this can be fixed without changing Axios. As @sanjai0py mentioned above, the content type is being set to a default in Axios. I believe it's actually being set [here](https://github.com/axios/axios/blob/cac6cfa6f6eda3fce45b658eafa07a70747a4652/lib/core/dispatchRequest.js#L46).

This code will only set the content type if there is no content type already specified. So if your server supports it, setting a different content type should help you circumvent the issue.

**Comment by betawait** [comment]
I did a bit more digging and was able to find a way to get Axios to remove the header. If content-type is set to `false` then it will be removed. I could get it to work by changing `packages\bruno-electron\src\ipc\network\prepare-request.js`, and will try to see if I can make a PR to fix it. But I need to do some more checks to make sure nothing breaks.

**Comment by betawait** [comment]
I created a PR for this here: https://github.com/usebruno/bruno/pull/3973

**Comment by anusree-bruno** [comment]
@betawait 
Thanks for the PR, we will look into this

**Comment by maintainer-bruno** [comment]
This issue has been resolved by [PR #3973](https://github.com/usebruno/bruno/pull/3973) and is now available in version 2.7.0.
Please update to the latest version to get the fix, and feel free to reach out if you encounter any further issues.

**Comment by chrishas35** [comment]
> This issue has been resolved by [PR #3973](https://github.com/usebruno/bruno/pull/3973) and is now available in version 2.7.0. Please update to the latest version to get the fix, and feel free to reach out if you encounter any further issues.

I am on 2.8.1 and seeing a `content-type:false` header when "No Body" is selected.

**Comment by marle3003** [comment]
I’m on Bruno 2.9.1 and this is still happening for me.
When sending a POST request with the "No Body" setting, Bruno still adds the Content-Type: application/x-www-form-urlencoded header

**Comment by sanjaikumar-bruno** [comment]
Hey @marle3003, with PR #3973 merged in [v2.7.0](https://github.com/usebruno/bruno/releases/tag/v2.7.0), a POST request with "No Body" should show `content-type:false` in the timeline. It seems the issue you’re having in 2.9.1 was already fixed in 2.7.0. Could you provide more details to help with debugging?

**Comment by helloanoop** [comment]
@chrishas35 @marle3003 A screen recording of the issue in action would be really helpful

**Comment by marle3003** [comment]
When sending a POST request with no body and no headers, Bruno behaves differently across platforms:

- On Windows: Bruno sends Content-Type: application/x-www-form-urlencoded
- On macOS: No Content-Type header is sent

Screenshot (Windows):
<img width="1256" height="750" alt="Image" src="https://github.com/user-attachments/assets/37e44d6f-0497-4112-b488-81b16ffb41be" />

**Comment by sreelakshmi-bruno** [comment]
Hi, we are currently investigating this and will provide an ETD by the end of this week. Thank you.

**Comment by sanjaikumar-bruno** [comment]
Hi @marle3003, I wasn't able to reproduce the issue you were facing.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e2cd78cd-28d2-49a4-8aee-d1a5fbefb17f" />

**Comment by clsknsmt-deontics** [comment]
this issue still appears to be present in the Bruno CLI client as of version 2.14.2. We are curently using `body:json` with no JSON body for every endpoint that fails without that. It appears to default to setting a request body of type `application/x-www-form-urlencoded` even though the files say `body:null`. Can you check again please?
