### ISSUE TITLE
Variables not working in multipart-form body

### ISSUE THREAD

**Issue by ftrudeau-pelcro** [usebruno/bruno#1763]
For the life of me, can't seam to make this work properly.

This works fine with a JSON body:

```
{
   "my_attribute_name": "{{my_attribute_value_generated_in_pre_request_script_and_set_using_bru.setVar}}"
}
```

When using `my_attribute_name` in a Multipart From body, the variable does not get evaluated. I literally get `{{my_attribute_value_generated_in_pre_request_script_and_set_using_bru.setVar}}` string posted as-is to the backend for Key `my_attribute_name`

**Version**:
Windows v1.10.0

**Comment by timwsuqld** [comment]
I'm also hitting this issue on v1.11.0 on Linux

**Comment by ftrudeau-pelcro** [comment]
This is a blocker. Any feedback here please?

**Comment by Its-treason** [comment]
> This is a blocker. Any feedback here please?

The merge request to fix it is still open: https://github.com/usebruno/bruno/pull/1217

But I merged the fix into my fork: https://github.com/Its-treason/bruno/releases/tag/nightly

**Comment by ftrudeau-pelcro** [comment]
Great, will close this then.

**Comment by timwsuqld** [comment]
@ftrudeau-pelcro not sure why you closed it, when it's still an issue in this repository? This should probably remain open until the MR is merged. It's great there is a fork we can use, but that doesn't fix the issue in mainline Bruno.
