### ISSUE TITLE
With Release 0.13.x something happend with the CLI.

### ISSUE THREAD

**Issue by mirkogolze** [usebruno/bruno#178]
With Release 0.13.x something happend with the CLI.
I use a piece of custom code to retrieve a bearer token with axios. So I need to use an async function and call it in the Pre Request Script.

```
  login: async function(tokenUrlKey = 'tokenUrl', clientIdKey = 'mapperClientId', clientSecretKey = 'mapperClientSecret', tokenKey = 'mapperToken') {

    let now = moment();
    let expiryTime = !!bru.getVar(tokenKey + 'tokenExpiryTime') ? moment(bru.getVar(tokenKey + 'tokenExpiryTime')) : now;
    let difference = expiryTime.diff(now, 'seconds');
    this.log('Token expires in seconds: ' + difference);

    let tokenUrl = bru.getEnvVar(tokenUrlKey);
    let mapperClientId = bru.getEnvVar(clientIdKey);
    let mapperClientSecret = bru.getEnvVar(clientSecretKey);

    // if expiring within 10 seconds
    if (difference < 10 || !bru.getVar(tokenKey + 'tokenExpiryTime')) { 
      this.log('Old token expired, requesting new one...');
      try {

        const data = {
          "grant_type": "client_credentials",
          "client_id": encodeURIComponent(mapperClientId),
          "client_secret": encodeURIComponent(mapperClientSecret)
        }

        let resp = await axios({
          method: 'POST',
          url: tokenUrl,
          headers: {
            "Accept": "application/json",
            "Content-Type": "application/x-www-form-urlencoded"
          },
          data: qs.stringify(data)
        });
        bru.setVar(tokenKey, resp.data.access_token);
        bru.setVar(tokenKey + 'tokenExpiryTime', moment().add(resp.data.expires_in, 'seconds').format());
        this.log('new token set.');
      
      } catch (error) {
        console.error(error);
        throw error;
      }
    }
    req.setHeader('Authorization', 'Bearer ' + bru.getVar(tokenKey));
    this.log('Auth Header set.');
  }
```

This works in the Bruno APP as expected. But in the CLI i now get
```
Running Folder

Folder\xxxxxx (await is only valid in async functions and the top level bodies of modules)
```

In the Bruno APP it is working fine as expected.
In the Bruno CLI now it does not work.
I tried to run the CLI from source code. Then the async block is running, but anything other ist happening.

**Comment by helloanoop** [comment]
Hi @mirkogolze 
It appears `bruno-cli` does not have the latest changes published to npm. The last publish was 4 months ago.
![image](https://github.com/usebruno/bruno/assets/9350733/94501823-908d-4162-b59e-03bd5b1382d3)

Since you were able to run it from the source code, I just published `0.6.0` 
Can you reinstall bruno cli and try the same.

@mirkogolze By the way - I see code like `this.log('Auth Header set.')` I am assuming this is a part of a class, and you are saving it as a js file inside the folder and importing this inside the pre request script. Would love to know how you are implementing this. And how are you able to see the logs.

**Comment by mirkogolze** [comment]
Hi @helloanoop,

thanks for publishing. But now I get the same result I got from the cli used out of the source code.
But the logging is working. Its only a console.log

my collections structure
```
|-- Mapper
|   |-- WriteAssemblyFrame.bru
|   |-- WritePlConnOrder.bru
|   |-- WritePlsEquipment.bru
|   `-- WritePlsEquipmentWrong.bru
|-- bruno.json
|-- environments
|   |-- Tardis-Local-Inhouse.bru
|-- package-lock.json
|-- package.json
`-- tools
    |-- tools.js
```

my tools.js
```
const axios = require('axios');
const moment = require('moment');
const qs = require('qs');

const tools = {

  log: function(str) {
    let now = moment().format();
    console.log(now + ' ' + str);
  },

  login: async function(tokenUrlKey = 'tokenUrl', clientIdKey = 'mapperClientId', clientSecretKey = 'mapperClientSecret', tokenKey = 'mapperToken') {

    let now = moment();
    let expiryTime = !!bru.getVar(tokenKey + 'tokenExpiryTime') ? moment(bru.getVar(tokenKey + 'tokenExpiryTime')) : now;
    let difference = expiryTime.diff(now, 'seconds');
    this.log('Token expires in seconds: ' + difference);

    let tokenUrl = bru.getEnvVar(tokenUrlKey);
    let mapperClientId = bru.getEnvVar(clientIdKey);
    let mapperClientSecret = bru.getEnvVar(clientSecretKey);

    // if expiring within 10 seconds
    if (difference < 10 || !bru.getVar(tokenKey + 'tokenExpiryTime')) { 
      this.log('Old token expired, requesting new one...');
      try {

        const data = {
          "grant_type": "client_credentials",
          "client_id": encodeURIComponent(mapperClientId),
          "client_secret": encodeURIComponent(mapperClientSecret)
        }

        let resp = await axios({
          method: 'POST',
          url: tokenUrl,
          headers: {
            "Accept": "application/json",
            "Content-Type": "application/x-www-form-urlencoded"
          },
          data: qs.stringify(data)
        });
        bru.setVar(tokenKey, resp.data.access_token);
        bru.setVar(tokenKey + 'tokenExpiryTime', moment().add(resp.data.expires_in, 'seconds').format());
        this.log('new token set.');
      
      } catch (error) {
        console.error(error);
        throw error;
      }
    }
    req.setHeader('Authorization', 'Bearer ' + bru.getVar(tokenKey));
    this.log('Auth Header set.');
  }
}

module.exports = tools;
```
And my pre Request Script:
```
const tools = require('./tools/tools');
await tools.login();
```

And now I see my console.logs, but the requests are not running
```
Running Folder

2023-09-01T09:50:33+02:00 Token expires in seconds: 0
2023-09-01T09:50:33+02:00 Old token expired, requesting new one...
Mapper\WriteAssemblyFrame (Request failed with status code 401)
2023-09-01T09:50:33+02:00 Token expires in seconds: 0
2023-09-01T09:50:33+02:00 Old token expired, requesting new one...
2023-09-01T09:50:33+02:00 new token set.
2023-09-01T09:50:33+02:00 Auth Header set.
Mapper\WritePlConnOrder (Request failed with status code 401)
2023-09-01T09:50:33+02:00 Token expires in seconds: 299
2023-09-01T09:50:33+02:00 Auth Header set.
2023-09-01T09:50:33+02:00 new token set.
2023-09-01T09:50:33+02:00 Auth Header set.
Mapper\WritePlsEquipment (Request failed with status code 500)
2023-09-01T09:50:33+02:00 Token expires in seconds: 299
2023-09-01T09:50:33+02:00 Auth Header set.
Mapper\WritePlsEquipmentWrong (Request failed with status code 500)

Tests:       0 passed, 0 total
Assertions:  0 passed, 0 total
```

In den Bruno APP this is working
![image](https://github.com/usebruno/bruno/assets/66121941/84d721c8-5181-41fd-afd5-a149e61aab73)

**Comment by helloanoop** [comment]
@mirkogolze I have released a fix for this in `0.6.1`
Can you install the latest version and check if it solves the issue.

PS:
Glad to see you using scripting in Bruno. This is the vision - that we can write custom javascript code in a js file and version it using git (or any scm). If your test involves complex assertions, they can be stored in a single place.
This also opens up a lot of possibilities.
Ex: A nightly run can be scheduled, and the test results can be mailed to the key stakeholders. (We will have to support some kind of a hook in bruno.json like `afterRun` that will be invoked with the test results to perform any action)

I am thinking something like
`bruno.json`
```js
{
  afterRun: "after-run.js"
}
```

`after-run.js`
```js
module.exports = function(err, results) {
   // do anything like - send a mail / send summary to grafana
}
```

I also plan on supporting view and editing of js files directly in the app itself.

**Comment by mirkogolze** [comment]
Hi  @helloanoop ,
there is still a problem running async tasks in the pre Request script.
![image](https://github.com/usebruno/bruno/assets/66121941/5b46ceda-5900-4c3c-b87a-2cb88212455b)
While starting the sandbox VM there is a missing await.
Same at starting the post request scripts.
I have fixed it locally and now it is working.
Would be cool when you could fix it again.

```
Index: packages/bruno-cli/src/runner/run-single-request.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/bruno-cli/src/runner/run-single-request.js b/packages/bruno-cli/src/runner/run-single-request.js
--- a/packages/bruno-cli/src/runner/run-single-request.js	(revision 08495e7fb5010777ee5077399d0723042be9c3c5)
+++ b/packages/bruno-cli/src/runner/run-single-request.js	(date 1693568472863)
@@ -36,7 +36,7 @@
     const requestScriptFile = get(bruJson, 'request.script.req');
     if(requestScriptFile && requestScriptFile.length) {
       const scriptRuntime = new ScriptRuntime();
-      scriptRuntime.runRequestScript(requestScriptFile, request, envVariables, collectionVariables, collectionPath);
+      await scriptRuntime.runRequestScript(requestScriptFile, request, envVariables, collectionVariables, collectionPath);
     }
 
     // interpolate variables inside request
@@ -63,7 +63,7 @@
     const responseScriptFile = get(bruJson, 'request.script.res');
     if(responseScriptFile && responseScriptFile.length) {
       const scriptRuntime = new ScriptRuntime();
-      scriptRuntime.runResponseScript(responseScriptFile, request, response, envVariables, collectionVariables, collectionPath);
+      await scriptRuntime.runResponseScript(responseScriptFile, request, response, envVariables, collectionVariables, collectionPath);
     }
 
     // run assertions

```

**Comment by helloanoop** [comment]
@mirkogolze I have made the changes and have published a patch release `0.6.2`

**Comment by mirkogolze** [comment]
Now it is running again. Cool

**Comment by helloanoop** [comment]
@mirkogolze Can you share your oauth 2.0 script in Scriptmania https://github.com/usebruno/bruno/discussions/385 ? It would benefit the community.
