### ISSUE TITLE
Make it possible to  retrieve the current environment name: bru.environment.name

### ISSUE THREAD

**Issue by MeTitus** [usebruno/bruno#2179]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

https://community.postman.com/t/extract-active-environment-name-within-script/1052/6

### Mockups or Images of the feature

bru.environment.name

**Comment by rafeanders** [comment]
`bru.getEnvName()`

Example in a script to do something different depending on environment:
```
switch (bru.getEnvName(this)) {
    case 'staging':
        do this;
        break;
    case 'production':
        do this other thing;
        break;
    default:
        console.log("Your not in any of those environments");
}
```

There is/was a bug with that however, involving `bru.setEnvVar` and I'm unsure if the fix has been merged yet.

**Comment by MeTitus** [comment]
I just tried it out and the bru.setEnvVar issue is still there.
Thanks for the help.

**Comment by MeTitus** [comment]
@Sirafe It does indeed :)

**Comment by Sirafe** [comment]
If this solves your request, could you close this request?
