### ISSUE TITLE
Getting a 415 Unsupported Media Type application/x-www-form-urlencode. when choosing No Body on a Put Request

### ISSUE THREAD

**Issue by ngerwig725** [usebruno/bruno#2323]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am using the desktop version,  I have a put request (works fine in Postman). I have a put request to retrieve a signed URL from an internal source.  I am passing the 5 pieces of required information in the query tab, the api-key in the header and choosing No Body in the body tab.  I am receiving a 415 unsupported media error 
{
  "Code": "UnsupportedMediaType",
  "Message": "Unsupported media type: application/x-www-form-urlencoded"
}

### Screenshots/Live demo link

Here is the timeline:
> PUT https://smbjaf8ibf.execute-api.us-east-1.amazonaws.com/wheatley-gateway/latest/blueprint/get_signed_url?institution_name=Institution_Name&environment=BAN83_954067357&filename=00725/BAN83_954067357/banner_compare_results.zip&fice=00725&production=False
> x-api-key: cannot send you that
< 415 Unsupported Media Type
< content-type: application/json
< content-length: 101
< connection: keep-alive
< date: Thu, 16 May 2024 14:45:52 GMT
< x-amzn-requestid: 2314781a-4a67-48fc-b635-5c32df74e0f5
< access-control-allow-origin: https://cloud-docs.10006.elluciancloud.com
< access-control-allow-headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key,X-Special-Header
< x-amz-apigw-id: X3lVDEN7oAMEPQg=
< access-control-expose-headers: X-Special-Header
< x-amzn-trace-id: Root=1-66461c20-5200460a0237b279055c6ab5;Parent=7cc434875fa01f14;Sampled=0;lineage=366a7af8:0
< access-control-max-age: 600
< access-control-allow-credentials: true
< x-cache: Error from cloudfront
< via: 1.1 1019c7748e9bd9371b8cbc3777f0a40e.cloudfront.net (CloudFront)
< x-amz-cf-pop: IAD79-C2
< x-amz-cf-id: _CU6mks2NR9o5DYJtWVVtqysruEtELBL4k6e9owcKAXfFTZSwJGBcQ==

**Comment by ngerwig725** [comment]
Using HTTPToolkit I captured the PUT request:
METHOD: PUT
URL
https://smbjaf8ibf.execute-api.us-east-1.amazonaws.com/wheatley-gateway/latest/blueprint/get_signed_url?institution_name=Institution%20Name&environment=BAN83_954067357&filename=00725/BAN83_954067357/banner_compare_results.zip&fice=00725&production=False
HEADERS
Accept:
application/json, text/plain, */*
Accept-Encoding:
gzip, compress, deflate, br
Connection:
keep-alive
Content-Length:
0
Content-Type:
application/x-www-form-urlencoded
Host:
smbjaf8ibf.execute-api.us-east-1.amazonaws.com
request-start-time:
1715954928121
User-Agent:
axios/1.6.8
x-api-key: redacted

Content type is being set to application/x-www-form-urlencoded even though I am choosing No Body

**Comment by sreelakshmi-bruno** [comment]
Hi @ngerwig725, can you check if this issue still persists on the latest version(1.34.2)? Thanks!

**Comment by ngerwig725** [comment]
This is still occuring in 1.36.1

**Comment by SFallon-SharpHat** [comment]
This is still occurring in 1.39.1 on Windows. I was able to work around it by setting the body type to JSON and just sending an empty object, but that might not work for everyone's APIs.

**Comment by betawait** [comment]
This should be fixed by the fix for https://github.com/usebruno/bruno/issues/1693, I've made a PR for that issue here: https://github.com/usebruno/bruno/pull/3973

**Comment by maintainer-bruno** [comment]
This issue has been resolved by [PR #3973](https://github.com/usebruno/bruno/pull/3973) and is now available in version 2.7.0.
Please update to the latest version to get the fix, and feel free to reach out if you encounter any further issues.

**Comment by jiangxiaoqiang** [comment]
> This issue has been resolved by [PR #3973](https://github.com/usebruno/bruno/pull/3973) and is now available in version 2.7.0. Please update to the latest version to get the fix, and feel free to reach out if you encounter any further issues.

2.7.0 still facing this error:

<img width="1382" height="805" alt="Image" src="https://github.com/user-attachments/assets/dc389b78-788c-4bb5-b910-f83363941ea5" />
