### ISSUE TITLE
Issue While using PKCS12 (.pfx) Certificate in the Request

### ISSUE THREAD

**Issue by sajid-akhtar** [usebruno/bruno#2631]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

We are invoking an API that uses SSL Validation policy and requires a Certificate to be included in the request from a trusted CA. However, Bruno is throwing an error. Complete details are mentioned below: 

**Error Message:** Error invoking remote method 'send-http-request': TypeError [ERR_INVALID_ARG_TYPE]: The "path"  argument must be of type string. Received undefined

**Certificate Type**: PKCS #12 (.pfx format - contains complete chain [Root, Intermediate and client] and private key)

**Steps Followed**:
- Select the Method. eg: GET
- Add the https url of the endpoint
- Add Basic Authentication Credentials
- Adding the certificate for the domain
- Making a request

**Steps Followed to Add the certificate for the domain**:
- Select the Collection
- Navigate to Client Certificates
- Enter the domain without https://
- Select type as PFX
- Choosing the file from the file system
- Providing the correct Passphrase
- Selecting Add

**OS**: Windows 10 Enterprise 22H2 (build: 19045.4529)
**Bruno Version**: v1.20.1

**Additional Information**:
- We used the Type (Cert) while adding the client certificates and it is working fine.
- We only have issues with the Type (PFX)
- We also tried with Postman in order to validate if the pfx certificate file is correct and it is working as expected.

**Replication of the Bug**:
- Please replicate the bug on your side by using any pfx certificate. The issue is with all CAs.
- Due to enterprise limitation, we will not be able to share details about endpoints and other details but you can replicate the bug easily on your side

### Screenshots/Live demo link

![error-message-pfx](https://github.com/user-attachments/assets/482d24b6-4a41-49bc-a1bb-153723102912)

**Comment by PHermanov** [comment]
Having the same issue

**Comment by tmnrtn** [comment]
Also experiencing this

**Comment by sanjai0py** [comment]
Hey @sajid-akhtar, thank you for taking the time to report this bug and for providing such a detailed bug report. The Bruno team is aware of this issue and is working on fixing it. We will update you once the fix is ready. Thanks!

**Comment by PHermanov** [comment]
@sajid-akhtar do you have any estimations in mind ?

**Comment by sanjai0py** [comment]
Hey @PHermanov, I think you tagged the wrong person here; it's OP. Anyways, the community can expect an update on the fix within a week.

**Comment by sanjai0py** [comment]
Hey @sajid-akhtar, the fix has been released in the latest version of Bruno. Please download the latest version [v1.22.0](https://github.com/usebruno/bruno/releases/tag/v1.22.0) After updating, could you please check and confirm if the issue has been resolved on your side as well? Thanks for your patience and for reporting the issue!

**Comment by PHermanov** [comment]
For me it no longer shows errors, but still not working. Server doesn't see the certificate

**Comment by sajid-akhtar** [comment]
Hi @sanjai0py The issue is resolved for me. Thank you so much for quick fix.

**Comment by sanjai0py** [comment]
Closing this issue is marked as resolved with thanks to @sajid-akhtar for taking the time to create this detailed bug report!
