### ISSUE TITLE
Lossless Serialization of Decimals and Large Numbers in JSON

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#2767]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

There are a number of issues related to
* Not able to handle large numbers
* Decimal numbers being converted as strings

We tried using [json-bigint](https://www.npmjs.com/package/json-bigint), but that didn't help.
We then tried using [lossless-json](https://www.npmjs.com/package/lossless-json), but that also failed at the axios layer with the below message

> Error occurred in handler for 'send-http-request': TypeError: Do not know how to serialize a BigInt
    at stringify (<anonymous>)
    at stringifySafely (/Users/anoop/bruno/bruno/node_modules/axios/dist/node/axios.cjs:1436:37)
    at Object.transformRequest (/Users/anoop/bruno/bruno/node_modules/axios/dist/node/axios.cjs:1496:14)
    at transform (/Users/anoop/bruno/bruno/node_modules/axios/dist/node/axios.cjs:1922:15)
    at Object.forEach (/Users/anoop/bruno/bruno/node_modules/axios/dist/node/axios.cjs:283:10)
    at Object.transformData (/Users/anoop/bruno/bruno/node_modules/axios/dist/node/axios.cjs:1921:11

### Related Issues:
* https://github.com/usebruno/bruno/issues/1753
* https://github.com/usebruno/bruno/issues/1768
* https://github.com/usebruno/bruno/issues/2376
* https://github.com/usebruno/bruno/issues/2438
* https://github.com/usebruno/bruno/issues/2043

### Related PRs:
* https://github.com/usebruno/bruno/pull/2006
* https://github.com/usebruno/bruno/pull/2236
* https://github.com/usebruno/bruno/pull/2382
* https://github.com/usebruno/bruno/pull/2736
* https://github.com/usebruno/bruno/pull/2449

### Solution
Do not compromise the fidelity of the Json string (by doing JSON parse and stringify) before the network request is made

**Comment by helloanoop** [comment]
PR #2773 has been merged, This will go out in the `v1.27.0` release.

**Comment by thomascaillier** [comment]
Hello,
There is still a bug in v1.34.1 where a too long value from API is displayed rounded.
Example : 1429599376132020**638** is displayed 1429599376132020**700**
However, when saving response to file (top right button), the .json contains the right value

**Comment by helloanoop** [comment]
@thomascaillier We have fixed this in [PR](https://github.com/usebruno/bruno/pull/6026) and is live in `v2.14.0` 🎉 🎉

**Comment by wishart-lbg** [comment]
I'm seeing this issue in v2.15.1 (is it the same) where a json response contains an Int64 value that gets rounded when saved to a variable to use in another request in a Bruno collection - is there a guide for handling big numbers?

**Comment by manglemix** [comment]
In v3.1.4, I am still getting this issue. The following is the JSON that is sent:
```json
{"user_event":{"queued_limit_order":{"order_id":269539466756291089,"unmatched":"1","price":"0.5"}}}
```

And this is what is received in Bruno:
```json
{
  "user_event": {
    "queued_limit_order": {
      "order_id": 269539466756291100,
      "unmatched": "1",
      "price": "0.5"
    }
  }
}
```
