### ISSUE TITLE
Bruno does not setup TLS anymore

### ISSUE THREAD

**Issue by riskersen** [usebruno/bruno#2877]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I'm trying to get access tokens from Entra, but it always fails with a 500 coming from our proxy server. As I checked the proxy logs, it was clear, that bruno does not setup TLS and is trying to send plaintext to a https endpoint. The Proxy is set as ENV Variable on system level and bruno is a portable version on Windows 10.

Unfortunately, the network log stays empty in developer tools, so I cannot provide more details except of the proxy error message

The issue appears when using built-in auth mechanism, script pane and also for direct API calls.

### Screenshots/Live demo link

Handshake failedThe SSL handshake could not be performed.Host: login.microsoftonline.comReason: Can't initialize server context:handshakefailed:server state 1:state 9:Application response 500 handshakefailedCompany Acceptable Use PolicyThis is an optional acceptable use disclaimer that appears on every page. You may change the wording or remove this section entirely in index.html.For assistance, please contact your system administrator.generated 2024-08-21 17:02:50 by McAfee Web Gatewayaxios/1.7.2 |   | Handshake failed | The SSL handshake could not be performed. | Host: login.microsoftonline.comReason: Can't initialize server context:handshakefailed:server state 1:state 9:Application response 500 handshakefailed | Company Acceptable Use Policy | This is an optional acceptable use disclaimer that appears on every page. You may change the wording or remove this section entirely in index.html. | For assistance, please contact your system administrator. | generated 2024-08-21 17:02:50 by McAfee Web Gatewayaxios/1.7.2

**Comment by riskersen** [comment]
I've created a tcpdump and noticed, that calls done by bruno are missing CONNECT calls:

dummy curl from windows:
![image](https://github.com/user-attachments/assets/212f1dac-478a-4f30-a628-293810fcd6a8)

vs bruno:
![image](https://github.com/user-attachments/assets/20b9782a-cba6-49eb-b3f5-4f1066fb4764)

So it seems, that bruno is not aware, that I'm using a proxy. The proxy variables are set by env vars and not within brunos config:

C:\Users\me>set
<snip>
HTTPS_PROXY=http://proxy.zz:3128
HTTP_PROXY=http://proxy.zz:3128
<snip>

**Comment by helloanoop** [comment]
Thanks for reporting this @riskersen 
We are in the final stages of getting a PR merged that will solve the issue around skipping the CONNECT call

We expect a fix to be released early next week.
cc @lohxt1 @byjrack

**Comment by byjrack** [comment]
And @riskersen likely it's all the same bug in Axios mentioned in #1372.  For https_proxy env Axios assumes that the scheme will be https and thus sends a TLS handshake before it would try and CONNECT.  Many proxies will just be listening on HTTP for efficiency so you get a variety of error conditions based on the proxy provider when the client sends the TLS handshake.  Been a long standing bug in Axios, but the Bruno crew are just going to be a bit more explicit as you can see in #2724 to avoid triggering the bad logic in Axios.

**Comment by bhecquet** [comment]
Hello, 

It seems that I have the same problem using the CLI.
With Bruno, I get
![image](https://github.com/user-attachments/assets/5e16bb4d-c462-41aa-a078-8d3148c413cd)

With Curl
![image](https://github.com/user-attachments/assets/2eb4bf29-0e60-4d2c-a050-33ec56fa2489)

The proxy is set through HTTPS_PROXY environment variable

**Comment by sreelakshmi-bruno** [comment]
Hi, apologies for the late response. This issue has been resolved as per our latest version 1.35, as we have added the option to choose 'System proxy' in Bruno. Please check it out and let me know how it goes. Thanks!

<img width="841" alt="Screenshot 2024-12-03 at 11 58 52 AM" src="https://github.com/user-attachments/assets/a2f209f6-cab3-41d4-b310-43c61507684c">

**Comment by bhecquet** [comment]
Hello @sreelakshmi-bruno 

I just tested your suggestion but I cannot make it work
In the application, I've set "system proxy" as suggested
In collection, I've set proxy to "global" (not sure if it's the right way)
I save collection, and execute it through the CLI on an other server that needs proxy access to go outside of our network

I get error "(Invalid URL)"

In the network capture I don't see any connection to the proxy

**Comment by sreelakshmi-bruno** [comment]
Hi @bhecquet, this setting would only work in the app at present. We're yet to add this feature to the CLI. Can you try using the GUI?

**Comment by bhecquet** [comment]
Hello @sreelakshmi-bruno , I don't have proxy on my windows machine, so It will be difficult for me to do the test. In our setup, proxy settings are only required for servers

**Comment by sreelakshmi-bruno** [comment]
We are working on a fix for the CLI. Will post updates here. Thanks!

**Comment by sreelakshmi-bruno** [comment]
Hi, can you test this issue with the beta version of CLI that I shared below and let me know if the problem persists? Thanks!
npm i @usebruno/cli-next@latest -g

**Comment by bhecquet** [comment]
Hello

I tested with 1.37 with support team and it works

**Comment by renalddubusedenred** [comment]
Hello,
On the latest version 1.37, System Proxy is not working using ZScaler application.
It seems that it does not recognize that a proxy is globally set.
What do you need to analyze?

**Comment by byjrack** [comment]
What is the error you are seeing?  My org uses z and is surfaced by a PAC and ztunnel.  1.37 seems to work fine in seeing the  proxy, but I am seeing issues w CA trust settings not applying.

**Comment by renalddubusedenred** [comment]
> What is the error you are seeing? My org uses z and is surfaced by a PAC and ztunnel. 1.37 seems to work fine in seeing the proxy, but I am seeing issues w CA trust settings not applying.

I want to call Azure WebService, which is secured by private endpoint.
ZScaler is used to allow this comunication.
Using Postman and system proxy setup, I have no problem
Using Bruno and system proxy, I get 403 - Forbidden error code.

**Comment by byjrack** [comment]
403 would indicate its reaching the Azure endpoint, but it's missing an Auth header so it's rejecting the connection.  Seems like Z and Bruno are fine together and I would look at your request to be sure the authorization is correct.

**Comment by sreelakshmi-bruno** [comment]
Hi, this issue has been resolved in 1.39. Please check it out.

**Comment by davidefalco** [comment]
Hello, with version 1.39.1 (portable), problem still exists. In my org a PAC proxy is used, I setted http_proxy and https_proxy envs and Bruno find them, but response returns a 403 error.

**Comment by renalddubusedenred** [comment]
Hello,
Version 1.40 fix the issue. System proxy is now working.
Thanks
