### ISSUE TITLE
Bruno can't access to collection level variables in Safe mode.

### ISSUE THREAD

**Issue by SPIRIT-00** [usebruno/bruno#2879]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno can't access to collection level variables in Safe mode. I guess it is.

### Screenshots/Live demo link

Failed GET request
![изображение](https://github.com/user-attachments/assets/7d1b5a01-303a-4a8f-a9fe-6c5861db63a8)
Collection level variable is defined
![изображение](https://github.com/user-attachments/assets/9d884320-2b22-4435-886a-201ac513382e)

In Dev mod all fine
![изображение](https://github.com/user-attachments/assets/4c7c5850-6cdc-4998-b04c-d33819ecba99)

**Comment by helloanoop** [comment]
Thanks for reporting the issue @SPIRIT-00 
We are taking a look at it.

**Comment by helloanoop** [comment]
@SPIRIT-00 IN the screenshot you shared, the api url in the first screenshot is different compared to the API in the second screenshot.

Are you using scripting to update the API endpoint?
Also are you using external npm modules in the collection (Safe mode does not support loading external modules)

**Comment by SPIRIT-00** [comment]
> @SPIRIT-00 IN the screenshot you shared, the api url in the first screenshot is different compared to the API in the second screenshot.
> 
> Are you using scripting to update the API endpoint? Also are you using external npm modules in the collection (Safe mode does not support loading external modules)

I use this pre-req script to set Endpoint. It takes request level variables and redefine url. Endpoint path on screen broken because scripts can't get collection and local variables values.

// url эндпоинта.
const isLink = bru.getRequestVar('isLink'), url = req.getUrl(), testField = bru.getRequestVar('testField'), findOneId = bru.getRequestVar('findOneId'), tooLongId = bru.getRequestVar('tooLongId'), notExistId = bru.getRequestVar('notExistId'), propName = bru.getRequestVar('propName'), propValue = bru.getRequestVar('propValue'), id1 = bru.getRequestVar('id1'), id2 = bru.getRequestVar('id2');
let targetUrl = ``, body = req.getBody();

if (isLink) {
  targetUrl = `/{{table}}/${id1}/{{linkWith}}/${id2}`;
} else {
  switch (req.method) {
    case 'POST': targetUrl = `/{{table}}`; break
    default: targetUrl = `/{{table}}/${findOneId}`; break
  }
}
req.setUrl(url + targetUrl);

**Comment by helloanoop** [comment]
Thanks for sharing this @SPIRIT-00 !
An issue related to `getRequestVar` api was also fixed in `v1.26.1`

Can you check if it solves your issue?

**Comment by SPIRIT-00** [comment]
> Thanks for sharing this @SPIRIT-00 ! An issue related to `getRequestVar` api was also fixed in `v1.26.1`
> 
> Can you check if it solves your issue?

Var that defined on collection level works correctly and i recive endpoin name.

But requset level defined var not resolved, you can see on screenshots
![изображение](https://github.com/user-attachments/assets/7c1247f3-8575-402b-9247-51afb3be94a7)
![изображение](https://github.com/user-attachments/assets/a381b63d-d3d7-431b-be8c-49e843f455c2)

**Comment by SPIRIT-00** [comment]
@helloanoop i think it issue resolved. Request level vars values can be received. But need create new issue about returned datatype of boolean values from request level vars.
As can tou see on screenshots in dev mode boolean like values returns as boolean. In safe mode boolean like values returns as strings.
