### ISSUE TITLE
Client Certificates not used on Auth when getting Access Token

### ISSUE THREAD

**Issue by PeterSimonis** [usebruno/bruno#3342]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When requesting an `OAuth 2.0` `Client Credentials` token on an Access Token URL which requires mTLS, the Client Certificates added to the collection are not used.

The UI displays `✅ Request made successfully`, even when the response is not a valid token response. In our case, it's a HTML page containing a Cloudflare error.

Writing a POST request using the `client_id`, `client_secret`, `grant_type` and `scope` in the body (`Content-Type` `application/x-www-form-urlencoded`) and providing Basic authorization in the `Authorization` header however, does take these Client Certificates into account. This then results in succesful retrieval of a token.

### .bru file to reproduce the bug

This .bru file demonstrates the request to succesfully retrieve a token through a POST request.
`client_secret` has been obfuscated

```
meta {
  name: Token
  type: http
  seq: 2
}

post {
  url: https://auth.test-datakluis.shared.topicuszorg.nl/oauth2/token
  body: formUrlEncoded
  auth: none
}

headers {
  Content-Type: application/x-www-form-urlencoded
  Authorization: Basic YnVyZ2VycG9ydGFsZW4tdGVzdC1jbGllbnQtY3JlZGVudGlhbHM6aW5zZXJ0X2NsaWVudF9pZF9oZXJl
}

body:form-urlencoded {
  grant_type: client_credentials
  scope: openid
  client_id: viplive
  client_secret: insert_client_id_here
}
```

### Screenshots/Live demo link

Client Credentials setup
![image](https://github.com/user-attachments/assets/fb6a39e6-12c8-47e2-bbd7-f67341ec08c4)

Result of Get Access Token from https://auth.test-datakluis.shared.topicuszorg.nl/oauth2/token:
![image](https://github.com/user-attachments/assets/3a4583cd-7876-4d6b-ba73-dff96cd98520)

**Comment by helloanoop** [comment]
Thanks for reporting this @PeterSimonis !

We’ll look into it and follow up with you soon.

**Comment by PeterSimonis** [comment]
Happy new year!
Any news on when development on this will start?

**Comment by PeterSimonis** [comment]
seems we have different definitions of "short-term-goal"
maybe @sreelakshmi-bruno can update me?

**Comment by sreelakshmi-bruno** [comment]
Hi @PeterSimonis, apologies for the delay in response. We've been working on an [OAuth 2.0 revamp](https://github.com/usebruno/bruno-experimental-builds/releases/tag/oauth2-revamp-v1.39.0-2025.1.24), which is currently in beta testing. We're currently working on adding support for Client credentials and it will likely go out in mid Feb. Thanks!

**Comment by anusree-bruno** [comment]
Can you update the version and check this has been resolved in the later version and OAuth2.0 is out. I am closing this issue, do reach out if this persists still.

**Comment by 7osema** [comment]
Hi @anusree-bruno @helloanoop,
I checked the last version (v2.4.0) and the problem is still there.

**Comment by KyleLJohnson** [comment]
Any update? The issue still exists

**Comment by jd-mkrn** [comment]
Hi, I'm also having the same issue on 2.8.1. Any update @sreelakshmi-bruno @anusree-bruno  ?

**Comment by anusree-bruno** [comment]
Hi @jd-mkrn We are checking this. Will get back to you

**Comment by anusree-bruno** [comment]
If the OAuth token endpoint (auth.example.com) and the resource endpoint (api.example.com) are on different subdomains, and your client certificate is restricted to one exact subdomain, the mTLS handshake may succeed for one endpoint but fail for the other.

This can be resolved by using a wildcard domain so the certificate matches across all subdomains.

Can you try updating it in:
Collection settings → Client Certificates → Domain
and set it to:

```
*.example.com
```
This will allow the same certificate to work for both auth.example.com and api.example.com (and any other subdomain), which might resolve the issue.

**Comment by Yanpas** [comment]
@anusree-bruno the problem still exists on macos, bruno v3.0.2

I have only one domain in the collection. The requests in the collection work smoothly, however the button "Get Access Token" fails (due to mtls error, saw this in timeline, got 400 status from backend).

**Comment by Yanpas** [comment]
I've vibecoded a fix, take a look, my gut feeling says that AI identified it correct
