### ISSUE TITLE
Bruno CLI: Auth doesn't work

### ISSUE THREAD

**Issue by HaikoF** [usebruno/bruno#3492]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have an auth by apikey in the headers defined for my endpoint. Using the Client works absolutely fine, but calling the same using the CLI it fails.
So, I tested to put the api-key directly into the header and the CLI execution was successful.
Also using Auth as queryparams fails but works if i put it directly into the Params.

Infrastructure: I'm checking an API endpoint in an azure APIManagement Service. All requests to this API operation get a 200 in return if the auth is correct.

### .bru file to reproduce the bug

meta {
  name: HealthCheck
  type: http
  seq: 1
}

head {
  url: {{ApimEndpoint}}/health
  body: none
  auth: apikey
}

auth:apikey {
  key: Ocp-Apim-Subscription-Key
  value: {{ApimKey}}
  placement: header
}

tests {
  test("Successful request", function () {
      expect(res.getStatus()).to.eql(200);
  });
}

### Screenshots/Live demo link

Running Request 

.\HealthCheck (401 Access Denied) - 98 ms
[Function: AssertionError]
AssertionError: expected 401 to deeply equal 200
    at VM2 Wrapper.apply (C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\node_modules\@usebruno\vm2\lib/bridge.js:485:11)
    at C:\Dev\Quorix\ApiTesting\vm.js:2:32
    at VM2 Wrapper.apply (C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\node_modules\@usebruno\vm2\lib\bridge.js:485:11)
    at C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\node_modules\@usebruno\js\src\test.js:3:11
    at VM2 Wrapper.apply (C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\node_modules\@usebruno\vm2\lib/bridge.js:485:11)
    at module.exports (C:\Dev\Quorix\ApiTesting\vm.js:1:94)
    at VM2 Wrapper.apply (C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\node_modules\@usebruno\vm2\lib\bridge.js:485:11)
    at TestRuntime.runTests (C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\node_modules\@usebruno\js\src\runtime\test-runtime.js:161:13)
    at runSingleRequest (C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\src\runner\run-single-request.js:341:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Users\client_se\AppData\Roaming\nvm\v20.18.0\node_modules\@usebruno\cli\src\commands\run.js:609:24) {
  showDiff: true,
  actual: 401,
  expected: 200,
  operator: 'strictEqual'
}
   ✕ Successful request

Requests:    1 passed, 1 total
Tests:       0 passed, 1 failed, 1 total
Assertions:  0 passed, 0 total
Ran all requests - 98 ms

Requests:    1 passed, 1 total
Tests:       0 passed, 1 failed, 1 total
Assertions:  0 passed, 0 total

**Comment by ganesh-bruno** [comment]
Hey @HaikoF,

Thanks for reporting this issue. I've been able to reproduce it. There seems to be an incompatibility with the CLI, and we're working on it.

**Comment by draialexis** [comment]
I'm having the same issue in 1.37.0

### A workaround

While they're working on a fix, instead of using

```
<verb> {
  url: ...
  body: ...
  auth: apikey
}

...

auth:apikey {
  key: {{API_KEY_HEADER}}
  value: {{API_KEY_SECRET}}
  placement: header
}
```

we can set that key-value pair in the headers ourselves like so

```
headers {
  {{API_KEY_HEADER}}: {{API_KEY_SECRET}}
}

```

**Comment by sreelakshmi-bruno** [comment]
Hi, this issue is resolved in the latest release of CLI. Please check it out and let me know how it goes. Thanks!

**Comment by HaikoF** [comment]
Hi!
Using Bru CLI 1.40.0 fixes the issue, but only if you set the authentication for the collection.
If I set the authentication for a single request, I still get an error:
```
Running Request

.\Health (401 Access Denied) - 287 ms
[Function: AssertionError]
AssertionError: expected 401 to deeply equal 200
    at VM2 Wrapper.apply (C:\Dev\...\node_modules\@usebruno\vm2\lib/bridge.js:485:11)
    at C:\Dev\...\vm.js:2:32
    at VM2 Wrapper.apply (C:\Dev\...\node_modules\@usebruno\vm2\lib\bridge.js:485:11)
    at C:\Dev\...\node_modules\@usebruno\js\src\test.js:3:11
    at VM2 Wrapper.apply (C:\Dev\...\node_modules\@usebruno\vm2\lib/bridge.js:485:11)
    at module.exports (C:\Dev\...\vm.js:1:94)
    at VM2 Wrapper.apply (C:\Dev\...\node_modules\@usebruno\vm2\lib\bridge.js:485:11)
    at TestRuntime.runTests (C:\Dev\...\node_modules\@usebruno\js\src\runtime\test-runtime.js:221:13)
    at runSingleRequest (C:\Dev\...\node_modules\@usebruno\cli\src\runner\run-single-request.js:474:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Dev\...\node_modules\@usebruno\cli\src\commands\run.js:820:24) {
  showDiff: true,
  actual: 401,
  expected: 200,
  operator: 'strictEqual'
}
   ✕ Successful request

Requests:    1 passed, 1 total
Tests:       0 passed, 1 failed, 1 total
Assertions:  0 passed, 0 total
Ran all requests - 287 ms

Requests:    1 passed, 1 total
Tests:       0 passed, 1 failed, 1 total
Assertions:  0 passed, 0 total
```
Thanks a lot @sreelakshmi-bruno !

**Comment by sreelakshmi-bruno** [comment]
Hi @HaikoF , thanks for getting back, we're working on adding authentication for single request in #4245.

**Comment by anusree-bruno** [comment]
This has been fixed in v2.3.0. Closing this issue. Feel free to reopen if you are still facing any issue regarding this
