### ISSUE TITLE
apt repository key has changed

### ISSUE THREAD

**Issue by kapouer** [usebruno/bruno#3569]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Err:12 http://debian.usebruno.com bruno InRelease                                             
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC

But the README gives 9FA6017ECABE0266.

While this might be some mishandling of the key (typically the belief that one needs a new key when it expires - it doesn't), it might also be sign of a compromised distribution channel !

### Screenshots/Live demo link

http://debian.usebruno.com/

**Comment by helloanoop** [comment]
Looking into this. It appears that the key might have expired although I remember setting it up for 2 years.

@kapouer Are you seeing this error when you run `apt update` ?

**Comment by kapouer** [comment]
Yes

**Comment by pantierra** [comment]
I am having the same problem.

Tried both:
```
sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 56333D3B745C1FEC
sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266
```

For `/etc/apt/sources.list.d/bruno.list`

```
 deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable
```

And I get for `apt update`:

```
Err:8 http://debian.usebruno.com bruno InRelease                                                                                                                                                  
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC
```

**Comment by RichAyotte** [comment]
APT has difficulty reading the `bruno.pgp` file so I exported it do `bruno.asc` and it's working fine now.

```bash
sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --export --armor | sudo tee /etc/apt/keyrings/bruno.asc > /dev/null
```
and
```
deb [signed-by=/etc/apt/keyrings/bruno.asc] http://debian.usebruno.com/ bruno stable
```

**Comment by pantierra** [comment]
Worked for me. Thanks!

**Comment by mlanner** [comment]
Exporting bruno.gpg to .asc didn't work for me. It just created a zero-byte file. Mainly commenting here to be notified when the issue has been solved.

**Comment by rdehouss** [comment]
Hello!
Same for me, changing to .asc didn't help.
Trying to import the missing key didn't help neither:
```sh
❯ sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 56333D3B745C1FEC
gpg: keybox '/etc/apt/keyrings/bruno.gpg' created
gpg: key 9FA6017ECABE0266: public key "Anoop M D <anoop.md1421@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by GodVenn** [comment]
+1

**Comment by egandro** [comment]
**Run this before the official documentation**

```bash
sudo mkdir -p /root/.gnupg/
sudo chmod 700 /root/.gnupg/
```

This hack helped!

(Something is broken and I have a lack of understanding why.)

I think this would be a better approach to just host the GPG key and make it's sha512 available.

```bash
wget https://foobar/debian/foo.gpg -O /etc/apt/trusted.gpg.d/foo.gpg 

# verify

sha512sum /etc/apt/trusted.gpg.d/foo.gpg 
cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e /etc/apt/trusted.gpg.d/foo.gpg 
```

**Comment by pedromtsilva** [comment]
@egandro hack solution worked as to use the gpg key! For some reason, the documentation command to download/make (not sure what is the operation) the GPG key is looking for the .gnupg/ directory in '/root/' directory.

Since the .gnupg/ directory is located in the home directory, would it be possible to use the user's home dir instead of root for the key installation?

Also, after removing the previously created /root/.gnupg/ directoryand everything was still working fine, so it seems like it really is just a key installation issue.

**Comment by egandro** [comment]
> 
> `gpg: WARNING: unsafe ownership on homedir '/home/<my-homedir>' `
> 

You need some `chmod 700 /home/whatever/.gnupg/`

**Comment by mathisgauthey** [comment]
As said in #1036, it was fixed in #1037 

This can now be closed I think @kapouer

**Comment by zoltan-sule** [comment]
someone should add the missing step to the downloads page because the info there results the same issue and people shouldn't read through the issues to understand what to do.

so please add this step to the https://www.usebruno.com/downloads page
`sudo gpg --list-keys`

**Comment by GarryG** [comment]
How is this not fixed in 8 months?

**Comment by mathisgauthey** [comment]
> How is this not fixed in 8 months?

As stated above it has been fixed mate. The only missing part would be the comment just above with the gpg list key stuff that is not yet I the doc, but feel free to create a scoped issue or PR to change that 🙏

**Comment by zoltan-sule** [comment]
wrong. The Debian based instructions on the downloads page are still not up-to-date. Those steps simply don't work without `sudo gpg --list-keys`

**Comment by mathisgauthey** [comment]
> wrong. The Debian based instructions on the downloads page are still not up-to-date. Those steps simply don't work without `sudo gpg --list-keys`

I stand corrected. Issue #1036 was supposedly fixed with #2356 and #1037 but I can´t see these changes either : 

[In the official download page](https://www.usebruno.com/downloads) : 

<img width="1232" height="449" alt="Image" src="https://github.com/user-attachments/assets/84840789-5be5-4404-b845-42f906c9e3ab" />

[In the official documentation](https://docs.usebruno.com/get-started/bruno-basics/download) : 

<img width="890" height="682" alt="Image" src="https://github.com/user-attachments/assets/62080e5b-5aa8-4940-ba73-7853956e8977" />

The only place where it changed is the [Github Readme](https://github.com/usebruno/bruno/?tab=readme-ov-file#installation) indeed. So use this one for now.

Maybe we should create a PR to update the official download page and the official documentation as a follow-up.

**Comment by anusree-bruno** [comment]
Doc update PR: https://github.com/usebruno/bruno-docs/pull/412

**Comment by jose-deniz-ns90** [comment]
As of today none of the instructions work with a trixie installation. What I used to be able to install in debian trixie
`sudo wget -O /etc/apt/keyrings/bruno.asc "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB5686F65CAA08C49040D6E3F56333D3B745C1FEC"`
`echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/bruno.asc] http://debian.usebruno.com/ bruno stable" | sudo tee /etc/apt/sources.list.d/bruno.list`

**Comment by LenhardErwan** [comment]
Thank you @jose-deniz-ns90, I couldn't get it to work either with Debian 13. With what you propose, it works like a charm.

**Comment by apahne** [comment]
Key appears to be expired:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. OpenPGP signature verification failed: http://debian.usebruno.com bruno InRelease: Sub-process /usr/bin/sqv returned an error code (1), error message is: Signing key on E598552E09C999055FEFA7159FA6017ECABE0266 is bad:            The primary key is not live   because: Expired on 2025-10-11T03:25:34Z
W: Failed to fetch http://debian.usebruno.com/dists/bruno/InRelease  Sub-process /usr/bin/sqv returned an error code (1), error message is: Signing key on E598552E09C999055FEFA7159FA6017ECABE0266 is bad:            The primary key is not live   because: Expired on 2025-10-11T03:25:34Z

```

**Comment by egandro** [comment]
This is the new key: <https://docs.usebruno.com/get-started/bruno-basics/download>

```bash
# Add the Bruno repository key
curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9FA6017ECABE0266" | gpg --dearmor | sudo tee /etc/apt/keyrings/bruno.gpg > /dev/null
```

A little glitch: it is now named ".gpg" your old source file might be still referencing ".asc" as extension. Fix the source file.

**Comment by votdev** [comment]
For anyone who is still encountering this issue. According to [README](https://github.com/usebruno/bruno/#installation) on GitHub, simply run:

```
$ sudo chmod 644 /etc/apt/keyrings/bruno.gpg
```

It looks like several pages have not been adapted to that.
- https://www.usebruno.com/downloads
- http://debian.usebruno.com/
- https://docs.usebruno.com/get-started/bruno-basics/download
