### ISSUE TITLE
Pre request scripts don't work in 1.36.1

### ISSUE THREAD

**Issue by MWDidata** [usebruno/bruno#3626]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Pre request scripts don't work anymore in 1.36.1,
I downgraded to 1.36, Pre request scripts work again.

The Variables don't get set.
The script is imported from Postman API

### .bru file to reproduce the bug

const moment = require('moment');
var currentDate = moment();

//StartTime First Hour
currentDate = moment();
const StartFirstHour = currentDate.format("yyyy-MM-DDT11:00:00");
bru.setVar('StartTimeFirstHour', StartFirstHour)

//EndTime First Hour
currentDate = moment();
const EndFirstHour = currentDate.format("yyyy-MM-DDT12:00:00");
bru.setVar('EndTimeFirstHour', EndFirstHour)

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/2b5eeb2e-d6a7-45e8-b710-41acf2b7ed11)
![image](https://github.com/user-attachments/assets/51385dc1-af06-45bd-9e38-07d8ba70b984)

**Comment by MWDidata** [comment]
This happens with CLI but also when running manually from the app

**Comment by MWDidata** [comment]
After trying to get a screen recording, I noticed that it does work from the app, just not from the CLI.

**Comment by MWDidata** [comment]
Is there any way to downgrade the CLI? I couldn't find a way to install the 1.36.0 CLI

**Comment by ganesh-bruno** [comment]
Hey @MWDidata,

Could you please try this in the latest version of the Bruno CLI? It was fixed in the latest release, and it should resolve the issue you're experiencing.

You can upgrade to the latest release by running the following command:

```
npm i @usebruno/cli@1.36.3
```

**Comment by MWDidata** [comment]
after installing the 1.36.3 version of the CLI, it still wont set those vars:
![image](https://github.com/user-attachments/assets/13b1f02d-3413-41f8-95ed-5b74aadc9299)

After installing version 1.36.0 it does work again. Thanks for the command I hope the issue can be fixed in upcomming releases

**Comment by MWDidata** [comment]
I tried on CLI version 1.35, This also did not work. 
Before the release of 1.36.1 it did work. 
Could there be anything else that would stop the vars from being set? in de app it works fine, 

EnvVars set during testrun with CLI also work, it's only variables that get set from the Collection that dont work.
I tried putting a string into one of those vars and this also did not get set.

If there is any more information I can give you let me know.

**Comment by ganesh-bruno** [comment]
Hey @MWDidata,

Thanks for reporting this issue.

I was able to reproduce it by my end and we're working on it.

**Comment by anusree-bruno** [comment]
Hi @MWDidata 
I tried this on versions 1.35.0, 1.36.0, 1.36.1, 1.36.2 and 1.36.3

The variables are setting on all these versions

You were saying that the version properties doesnt change? is the version always remaining on 1.36.2?
I intstalled it globally and for me it is getting updated as per the version
<img width="608" alt="Screenshot 2025-01-02 at 15 13 32" src="https://github.com/user-attachments/assets/51eeee9c-a97d-49a6-8f93-702f4e0013c1" />

**Comment by MWDidata** [comment]
For version 1.37.0 the main issue of pre-request variables not being set with CLI run has been fixed, As for other problems I found I thinks its best to create a new ticket if I run into them again.

Thanks for the help!
