### ISSUE TITLE
Interpolate collection vars in Generate Code

### ISSUE THREAD

**Issue by bhaugeea** [usebruno/bruno#3824]
### I have checked the following:

- [x] I use the newest version of bruno.
- [x] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Collection-level variables are not interpolated in Generate Code: the `{{var}}` is URL-escaped and included as-is.

### .bru file to reproduce the bug

bruno.json
{
  "version": "1",
  "name": "bug",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ]
}

bug.bru
meta {
  name: bug
  type: http
  seq: 2
}

get {
  url: http://localhost/bug/{{var}}
  body: none
  auth: none
}

collection.bru
vars:pre-request {
  var: var-value
}

### Screenshots/Live demo link

![Image](https://github.com/user-attachments/assets/3efeb3b0-aa4c-400d-bb99-0c9746e1d212)

![Image](https://github.com/user-attachments/assets/968c13a9-b63a-42f2-81fc-fc4d01de46be)

![Image](https://github.com/user-attachments/assets/d5f5eb07-8951-4eb0-854b-4d6490096cb2)

**Comment by ganesh-bruno** [comment]
Hey @bhaugeea,

Thanks for reporting this issue. We're aware of it and are working on it.

Also, thank you for submitting the PR! We're looking into it.

**Comment by pooja-bruno** [comment]
Hey @bhaugeea, this issue has been fixed in our latest build. Feel free to try it out and let us know if you run into anything else. Closing this now — thanks for reporting it!

**Comment by andreikubar** [comment]
somehow on macOS with latest version 2.9.1 interpolation still doesn't work...
<img width="801" height="166" alt="Image" src="https://github.com/user-attachments/assets/d46652d5-5735-42ae-945e-860fe56f94b9" />

**Comment by pooja-bruno** [comment]
This issue will be fixed in version 2.10.0. Here’s the [PR](https://github.com/usebruno/bruno/pull/5187)
