### ISSUE TITLE
Json validation with substitution of boolean and integer values from vars not working

### ISSUE THREAD

**Issue by mark99i** [usebruno/bruno#442]
I use json body for post requests and vars to substitute changeable values when testing the api, everything is fine with inserting str, but when I try to insert int or bool or list, json validation stops working.

![image (3)](https://github.com/usebruno/bruno/assets/46539611/5ae12d54-91d3-494e-b87d-a0068087c8f1)
![image3](https://github.com/usebruno/bruno/assets/46539611/11506a81-86dc-4d0a-93d2-467300e1ee6b)

**Comment by anusree-bruno** [comment]
This issue is resolved in the later versions.

**Older version v1.33.0:**

<img width="1131" alt="Image" src="https://github.com/user-attachments/assets/b9287233-63e7-462a-9132-11516bd551a2" />

**Current v2.2.0:**
<img width="1131" alt="Image" src="https://github.com/user-attachments/assets/66e468e0-1657-434b-9b7f-e64ede187f8b" />

Closing this issue. Feel free to reopen if this persists or is not resolved completely

**Comment by shinmawa** [comment]
@anusree-bruno  - Recommend reopening the issue.   It was not resolved, not even in your screenshot.

In your screenshot, the JSON format validation breaks immediately after {{booleanValue}}, causing "array" to be shown as invalid.

Here is another example where the issue is starkly apparent, breaking after the numerical value "topK":

(Version 2.8.0)
<img width="903" height="572" alt="Image" src="https://github.com/user-attachments/assets/6b205d99-169e-4114-b9e2-75e4fe14dd10" />

As an aside, the JSON Prettifier pretty much destroys the document after that point as well.

<img width="907" height="822" alt="Image" src="https://github.com/user-attachments/assets/59f1cd3e-0c4f-4b79-9461-0ccf8f3a3a48" />

**Comment by anusree-bruno** [comment]
Apologies, I mistook the issue for something else — you’re right, the formatter is still broken. Reopening this now. The second issue is being tracked separately here: https://github.com/usebruno/bruno/issues/3019.

**Comment by kejdajar** [comment]
I can confirm that this issue is still present in v3.2.2. For instance, the following example breaks the JSON syntax highlighter in a POST request body:
```json
{
  "object": {
    "aray1": [
      {{$randomInt}}, {{$randomInt}}
    ],
    "property1": "value"
  }
}
```
