### ISSUE TITLE
Error "Not Found" when renaming a request with an open tab.

### ISSUE THREAD

**Issue by felipebossolani** [usebruno/bruno#460]
**Description**:
Whenever I have an open tab for a specific request and try to rename it from the left-hand side menu, I encounter a "Not Found" error.

**Steps to reproduce**:
1. Open a tab for any request.
2. Rename the request on left-side.

**Expected behavior**:
The tab should update with the new request name without any error.

**Actual behavior**:
The tab shows an error message: "Request no longer exists. This can happen when the .bru file associated with this request was deleted on your filesystem."

**Screenshots**:
Running before request rename
<img width="883" alt="image" src="https://github.com/usebruno/bruno/assets/24377387/57c809c2-3a81-4629-a6da-220d5d5b8f17">

After rename
<img width="876" alt="image" src="https://github.com/usebruno/bruno/assets/24377387/1b8ad913-298b-4045-9279-2ccbf404bd70">

**Environment**:
- OS: Windows 11
- Version of the tool: 0.21.1

**Comment by srikary12** [comment]
It's working fine on Mac v0.21.0

**Comment by not-known-person** [comment]
I can confirm that I've replicated and verified this issue on Windows 11.

**Comment by not-known-person** [comment]
After investing considerable time in debugging the issue, I have identified a key observation. It appears that when we rename a request, the unique identifier (UID) associated with that request changes. However, the activeTabPanel ID remains constant throughout the process. This difference presents a problem because the application relies on the activeTabUID to locate and identify specific items, and when we rename a request, the associated unique identifier (UID) changes unexpectedly. I am currently investigating the underlying reasons for the request ID to undergo changes upon renaming, as this behavior is not yet fully understood.
@helloanoop  Any suggestion from your side ?

**Comment by xolve** [comment]
This also happens if you move or delete a request.

![image](https://github.com/usebruno/bruno/assets/520649/64b1bdc3-3095-4250-a009-44f3b2efe3c9)

**Comment by l0new4nder3r** [comment]
Indeed, when renaming an opened request, the behaviour could be: switch to the new one (if behind the scenes delete + create operations are performed). 

_This would seem less confusing for the user, imho._

**Comment by helloanoop** [comment]
@xolve Which version of Bruno are you using? This issue is fixed in the latest releases of Bruno.

**Comment by xolve** [comment]
Still happening with latest version on rename:

![image](https://github.com/usebruno/bruno/assets/520649/c3d6c056-df5b-4b45-bcd8-2e77fe92e8d5)

**Comment by deepee2** [comment]
Still happing with Bruno 1.7.1 (Win10 22H2) and can be reproduced easily
![bruno_rename_errormessage](https://github.com/usebruno/bruno/assets/11028366/b9b1cfd3-815f-42da-93a9-b67609a9af94)

**Comment by helloanoop** [comment]
This has been fixed in #3192 and will be released in the upcoming `v1.32.0` release
