### ISSUE TITLE
Getting like this whenever tried to use POST method "Oops! Something went wrong If you are using an official production build: the above error is most likely a bug! Please report this under:https://github.com/usebruno/bruno/issues"

### ISSUE THREAD

**Issue by noothanbalusu6** [usebruno/bruno#5061]
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [x] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

1.36.1

### Operating System

windows 11

### Describe the bug

<img width="356" height="226" alt="Image" src="https://github.com/user-attachments/assets/4f2e0fe8-72e8-42e1-983b-3b73dce4d8f8" />

### Screenshots/Live demo link

<img width="356" height="226" alt="Image" src="https://github.com/user-attachments/assets/6cbadbba-43a1-4577-b24b-98879519d9e3" />

**Comment by anusree-bruno** [comment]
Could you try again using the latest version? You can download it here: https://www.usebruno.com/downloads

If this persists in the latest version too then: 
Please open the console (Ctrl/Cmd + Shift + I) — or click the meatball icon in the app

<img width="369" height="350" alt="Image" src="https://github.com/user-attachments/assets/aa707ddf-a43d-47fe-b958-5f24de44fa91" />

 and select Chrome Console — and share any error logs you see there.

You mentioned this happens with a POST request — is it for all POST requests or just a specific one? If it’s specific, could you share the corresponding .bru file (feel free to mask any sensitive info)?

**Comment by rkgain** [comment]
<img width="960" height="503" alt="Image" src="https://github.com/user-attachments/assets/1c729d75-4f20-4c7b-aac3-8ff89c225ad2" />

**Comment by anusree-bruno** [comment]
Is this on the latest version 2.8.1?
See related issue https://github.com/usebruno/bruno/issues/4573, where this was fixed

**Comment by nikhilaKalvaFC** [comment]
This bug still persists on latest version V2.13.2 as well. When I click on run collection I get the above shown error screen. I am running it in Developer mode and I cannot see the "Chrome console" thing popped up. 

<img width="501" height="399" alt="Image" src="https://github.com/user-attachments/assets/7533326b-2808-4753-8b25-90a2a6680792" />

This occurs for individual request as well as running as a collection

**Comment by anusree-bruno** [comment]
Hi @nikhilaKalvaFC,
Could you please open the console using `Ctrl/Cmd + Shift + I` and share a screenshot of the error message? That will help us understand what’s going on.
Also, is this issue occurring for all collection runs, or just a specific collection?
