### ISSUE TITLE
Unable to make external API Call via proxy

### ISSUE THREAD

**Issue by fctg-kandasas** [usebruno/bruno#6086]
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [x] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

2.14.1

### Operating System

Windows 11

### Describe the bug

Unable to make external API call.

Getting error as : `write EPROTO 60223040:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:127:`

<img width="863" height="691" alt="Image" src="https://github.com/user-attachments/assets/19b6da98-b1bf-46ce-9add-91518dbeb6e7" />

### .bru file to reproduce the bug

[bruno.json](https://github.com/user-attachmen

[Sample API Collection.zip](https://github.com/user-attachments/files/23520504/Sample.API.Collection.zip)

ts/files/23520488/bruno.json)

### Screenshots/Live demo link

<img width="863" height="691" alt="Image" src="https://github.com/user-attachments/assets/19b6da98-b1bf-46ce-9add-91518dbeb6e7" />

**Comment by Pragadesh44-Bruno** [comment]
Thanks for reporting this issue. However, I need the `bruno.json` file for the specified collection to investigate the cause.

**Comment by fctg-kandasas** [comment]
> Thanks for reporting this issue. However, I need the `bruno.json` file for the specified collection to investigate the cause.

please find the attached. Its the sample one which we got from bruno
[bruno.json](https://github.com/user-attachments/files/23521844/bruno.json)

**Comment by sreelakshmi-bruno** [comment]
Closing this ticket since this issue has been fixed. Please reopen if you find otherwise, thanks!

**Comment by fctg-kandasas** [comment]
HI @sreelakshmi-bruno I am still facing this issue with Version Bruno 3.2.0
