### ISSUE TITLE
Can't create environment variable with a "." in the name (Postman import issue)

### ISSUE THREAD

**Issue by ljohnston** [usebruno/bruno#964]
Similar to #853 ... We have Postman environments with variable names like `some.service.url`. This creates issues in Bruno when importing a Postman collection (where variable names with dots are allowed). After importing a Postman collection that has requests defined as `GET {{some.service.url}}/api/v1/...`, for example, you can't create an environment variable in Bruno that will allow that request to be sent. To get things to work, you'd first have to modify every request imported from the collection to remove the dots.

**Comment by helloanoop** [comment]
@ljohnston This has been fixed in `v1.3.0`

**Comment by ljohnston** [comment]
@helloanoop - Thanks... that's awesome! While it gets me one step closer to fully replacing Postman with Bruno, I still can't just yet due to #799.
